apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
  - name: web-port
    port: 80  # 로드밸런서에 접근하기 위한 포트
    targetPort: 80